Repository makerdao/mips, pull requests merged in 2022-09, with the labels that each got.

#649 fix typo and link
  MIP39/mip39.md
Labels: typo fix

#644 Sync Proposals
  MIP1/MIP1c4-Subproposals/MIP1c4-SP1.md
  MIP1/MIP1c4-Subproposals/placeholder.md
  MIP38/mip38.md
  MIP39/MIP39c2-Subproposals/MIP39c2-SP35.md
  MIP39/MIP39c2-Subproposals/MIP39c2-SP36.md
  MIP39/MIP39c2-Subproposals/MIP39c2-SP37.md
  MIP39/MIP39c3-Subproposals/MIP39c3-SP3.md
  MIP39/MIP39c3-Subproposals/MIP39c3-SP4.md
  MIP39/MIP39c3-Subproposals/MIP39c3-SP5.md
  MIP39/mip39.md
  MIP4/MIP4c2-Subproposals/MIP4c2-SP27.md
  MIP4/MIP4c4-Subproposals/MIP4c4-SP1.md
  MIP41/MIP41c5-Subproposals/MIP41c5-SP9.md
  MIP41/mip41.md
  MIP55/MIP55c3-Subproposals/MIP55c3-SP7.md
  MIP80/MIP80.md
  MIP83/MIP83.md
  MIP84/MIP84.md
  MIP85/MIP85.md
Labels: RFC

#650 Obsolete mips comments
  MIP3/mip3.md
  MIP5/mip5.md
Labels: Miscellaneous fix

#653 fix spelling error
  MIP40/MIP40c3-Subproposals/MIP40c3-SP79.md
Labels: typo fix

#665 add line breaks
  MIP86/MIP86.md
Labels: typo fix
